version: '3'
services:
  app:
    image: bank
    ports:
      - 8080-8081:8080
    restart: on-failure
    depends_on:
      - postgres

  postgres:
     image: postgres
     container_name: postgres
     environment:
       POSTGRES_PASSWORD: mysecretpassword
       POSTGRES_USER: sa
     ports:
       - 5432:5432



