version: '3'
services:
  app:
    image: bank
    container_name: bank
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres

    networks:
      - mybridge

  postgres:
     image: postgres
     container_name: postgres
     environment:
       POSTGRES_PASSWORD: mysecretpassword
       POSTGRES_USER: sa
     ports:
       - 5432:5432
     networks:
       - mybridge

networks:
  mybridge:
    name: mybridge
    driver: bridge



